apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: ron1111000/users:latest
          env:
            - name: PORT
              valueFrom:
                secretKeyRef: 
                  name: users-secrets
                  key: PORT
            - name: USERS_DB_URI
              valueFrom:
                secretKeyRef: 
                  name: users-db-uri
                  key: USERS_DB_URI
            - name: JWT_KEY
              valueFrom:
                secretKeyRef: 
                  name: jwt-key
                  key: JWT_KEY
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef: 
                  name: users-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: users-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef: 
                  name: users-secrets
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                secretKeyRef: 
                  name: users-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef: 
                  name: users-secrets
                  key: DB_PORT
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef: 
                  name: rabbitmq-url
                  key: RABBITMQ_URL
            - name: PROXY_URL
              valueFrom:
                secretKeyRef: 
                  name: proxy-url
                  key: PROXY_URL
            - name: NODE_ENV
              valueFrom:
                secretKeyRef: 
                  name: node-env
                  key: NODE_ENV
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      