apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: ron1111000/client
      context: ../Frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.tsx
            dest: .
    - image: ron1111000/proxy
      context: ../Proxy
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: ron1111000/users
      context: ../BackendUserService
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: ron1111000/movies
      context: ../BackendMoviesService
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: ron1111000/payments
      context: ../BackendPaymentService
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: ron1111000/ai
      context: ../BackendAiService
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .