apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - net-flex-prod.site
      secretName: proxy-ingress-tls
  rules:
    - host: net-flex-prod.site
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: proxy-srv
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 5173