apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
        - name: ai
          image: ron1111000/ai:latest
          env: 
            - name: PORT
              valueFrom:
                secretKeyRef: 
                  name: ai-secrets
                  key: PORT
            - name: REDIS_URI
              valueFrom:
                secretKeyRef:
                  name: redis-uri
                  key: REDIS_URI
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef: 
                  name: redis-port
                  key: REDIS_PORT
            - name: AI_DB_URI
              valueFrom:
                secretKeyRef: 
                  name: ai-db-uri
                  key: AI_DB_URI
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef: 
                  name: groq-api-key
                  key: GROQ_API_KEY
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef: 
                  name: gemini-api-key
                  key: GEMINI_API_KEY
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef: 
                  name: rabbitmq-url
                  key: RABBITMQ_URL
            - name: PROXY_URL
              valueFrom:
                secretKeyRef: 
                  name: proxy-url
                  key: PROXY_URL
            - name: NODE_ENV
              valueFrom:
                secretKeyRef: 
                  name: node-env
                  key: NODE_ENV
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"