apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      initContainers:
        - name: wait-for-rabbit
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;']
      containers:
        - name: payments
          image: ron1111000/payments:latest
          env: 
            - name: PORT
              valueFrom:
                secretKeyRef: 
                  name: payments-secrets
                  key: PORT
            - name: DB_URI
              valueFrom:
                secretKeyRef: 
                  name: payments-secrets
                  key: DB_URI
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef: 
                  name: payments-secrets
                  key: RABBITMQ_URL
            - name: PROXY_URL
              valueFrom:
                secretKeyRef: 
                  name: payments-secrets
                  key: PROXY_URL
            - name: NODE_ENV
              valueFrom:
                secretKeyRef: 
                  name: payments-secrets
                  key: NODE_ENV
            - name: PAYPAL_CLIENT_ID
              valueFrom:
                secretKeyRef: 
                  name: payments-secrets
                  key: PAYPAL_CLIENT_ID
            - name: PAYPAL_SECRET
              valueFrom:
                secretKeyRef: 
                  name: payments-secrets
                  key: PAYPAL_SECRET
            - name: PAYPAL_API_BASE_URL
              valueFrom:
                secretKeyRef: 
                  name: payments-secrets
                  key: PAYPAL_API_BASE_URL
            - name: PAYPAL_PLAN_ID
              valueFrom:
                secretKeyRef: 
                  name: payments-secrets
                  key: PAYPAL_PLAN_ID
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"     