apiVersion: v1
kind: Secret
metadata:
  name: payments-secrets
type: Opaque
stringData:
  DB_URI: "mysql://root:kZUPoOLfZWPTysMvVYZfXDWYpYOMNWGH@crossover.proxy.rlwy.net:29789/railway"
  RABBITMQ_URL: "amqps://nnzejzwb:Vf4pSOdIu1bF7Tt77e_c9e8gjkChp0JS@cow.rmq2.cloudamqp.com/nnzejzwb"
  PROXY_URL: "http://proxy:5000"
  NODE_ENV: "development"
  PORT: "4001"
  PAYPAL_CLIENT_ID: "AY7NUICQ2Sjh-8J9tVjGAIaMXGfwwAE-QNVyN_bUfUYT9Zew3nh1gDmq5NdAjBFgPF3IHHsEfYJS7qwV"
  PAYPAL_SECRET: "EJZzEQAVL4g4Bgo4VnXVtR9uhRqam3x1-jKdMUpkklLj0e62hM7CSY1xbqNyTzKrH58ECThOIP-0wHVK"
  PAYPAL_API_BASE_URL: "https://api-m.sandbox.paypal.com"
  PAYPAL_PLAN_ID: "P-0RX17426M5887602LM72HD4Q"

  #  RABBITMQ_URL: "amqp://rabbitmq"