apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
        - name: movies
          image: ron1111000/movies:latest
          env: 
            - name: PORT
              valueFrom:
                secretKeyRef: 
                  name: movies-secrets
                  key: MOVIES_PORT
            - name: REDIS_URI
              valueFrom:
                secretKeyRef: 
                  name: redis-uri
                  key: REDIS_URI
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef: 
                  name: redis-port
                  key: REDIS_PORT
            - name: API_READ_ACCESS_TOKEN
              valueFrom:
                secretKeyRef: 
                  name: api-read-access-token
                  key: API_READ_ACCESS_TOKEN
            - name: API_KEY
              valueFrom:
                secretKeyRef: 
                  name: api-key
                  key: API_KEY
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef: 
                  name: rabbitmq-url
                  key: RABBITMQ_URL
            - name: PROXY_URL
              valueFrom:
                secretKeyRef: 
                  name: proxy-url
                  key: PROXY_URL
            - name: NODE_ENV
              valueFrom:
                secretKeyRef: 
                  name: node-env
                  key: NODE_ENV
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"