name: tests-payment

on:
  pull_request:
      paths:
        - 'BackendPaymentService/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd BackendPaymentService && npm install && npm run test:ci
      
