name: tests-user

on:
  pull_request:
      paths:
        - 'BackendUserService/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd BackendUserService && npm install && npm run test:ci
      
